let jobs=[]; let profile={}; let currentJob=null;
const meta={dashboard:['Good morning, Rajesh.','Your career agent is now connected to a local data layer.'],matches:['Job Matches','AI-ranked opportunities aligned to your verified career profile.'],review:['Application Review','Analyze a job, generate an application package, then approve it.'],applications:['Applications','Track opportunities from discovery through human-approved submission.'],profiles:['Resume Profiles','Master profile and targeted personas used for tailoring.'],messages:['Messages','AI-generated outreach based only on verified profile facts.'],analytics:['Career Analytics','Measure application and interview conversion.'],settings:['Agent Settings','Control matching, AI provider and human-approval rules.'],intake:['Job Intake','Paste a job description and turn it into a scored opportunity.']};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url,opts){const r=await fetch(url,opts);const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j;}
async function load(){jobs=await api('/api/jobs'); profile=await api('/api/profile'); render('dashboard');}
function rows(list=jobs){return list.map(j=>`<div class="job"><div><b>${esc(j.title)}</b><div class="muted">${esc(j.company)} · ${esc(j.location)}</div></div><div><span class="score">${j.score}%</span><div class="muted">match</div></div><div><span class="pill ${String(j.status).includes('Ready')||String(j.status).includes('Approved')?'green':''}">${esc(j.status)}</span></div><button class="btn" onclick="openReview('${j.id}')">Review</button></div>`).join('')}
function render(p){document.getElementById('page-title').textContent=meta[p][0];document.getElementById('sub').textContent=meta[p][1];document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.p===p));let c='';
if(p==='dashboard')c=`<div class="grid"><div class="card"><span class="muted">New Matches</span><div class="metric">${jobs.length}</div><span class="green">Live local data</span></div><div class="card"><span class="muted">High Match</span><div class="metric">${jobs.filter(j=>j.score>=90).length}</div><span class="green">≥ 90% fit</span></div><div class="card"><span class="muted">Approved</span><div class="metric">${jobs.filter(j=>String(j.status).includes('Approved')).length}</div><span class="green">Human approved</span></div><div class="card"><span class="muted">AI Provider</span><div class="metric" id="ai-status">—</div><span class="muted">Server configuration</span></div></div><div class="section"><h2>Priority matches</h2><div class="jobs">${rows([...jobs].sort((a,b)=>b.score-a.score).slice(0,6))}</div></div><div class="section card"><h3>Phase 2 Agent Run</h3><p class="muted">Jobs are persisted locally in <code>data/jobs.json</code>. Add a JD, score it, analyze it, and approve the package before any human submission.</p></div>`;
else if(p==='matches')c=`<div class="section"><div class="actions" style="margin:0 0 12px"><button class="btn primary" onclick="page('intake')">+ Add Job / JD</button></div><div class="jobs">${rows([...jobs].sort((a,b)=>b.score-a.score))}</div></div>`;
else if(p==='intake')c=`<div class="panel"><h3>Add a job</h3><div class="formgrid"><input id="company" placeholder="Company"/><input id="job-title" placeholder="Job title"/><input id="location" placeholder="Location"/><input id="source" placeholder="Source (LinkedIn, Naukri, referral...)"/></div><textarea id="description" rows="14" placeholder="Paste the full job description here..."></textarea><div class="actions"><button class="btn primary" onclick="addJob()">Save & Score Job</button></div><div id="intake-result"></div></div>`;
else if(p==='review')c=reviewHtml(currentJob||jobs[0]);
else if(p==='applications')c=`<div class="panel">${rows(jobs).replaceAll('Review','Open')}</div>`;
else if(p==='profiles')c=`<div class="profilegrid">${['Master Career Profile','Senior QE Manager','QE Transformation','QE Architect / Test Architect','AI / Agentic QE'].map((x,i)=>`<div class="card"><h3>${x}</h3><p class="muted">${i?'Targeted application persona':'Source of truth — '+profile.experience+' QE leadership.'}</p><div class="factor"><span>Core skills</span><b>${i?profile.skills.slice(0,5).join(' · '):profile.skills.slice(0,6).join(' · ')}</b></div><span class="pill">Auto-tailor enabled</span></div>`).join('')}</div>`;
else if(p==='messages')c=`<div class="profilegrid"><div class="card"><h3>Recruiter outreach</h3><p class="muted">Generated per job from verified profile facts.</p></div><div class="card"><h3>Hiring-manager outreach</h3><p class="muted">Focuses on transformation outcomes and leadership.</p></div><div class="card"><h3>Referral request</h3><p class="muted">Short, role-specific and editable.</p></div><div class="card"><h3>Application follow-up</h3><p class="muted">Prepared after human-approved submission.</p></div></div>`;
else if(p==='analytics')c=`<div class="grid"><div class="card"><span class="muted">Opportunities</span><div class="metric">${jobs.length}</div></div><div class="card"><span class="muted">≥90% Fit</span><div class="metric">${jobs.filter(j=>j.score>=90).length}</div></div><div class="card"><span class="muted">Approved</span><div class="metric">${jobs.filter(j=>String(j.status).includes('Approved')).length}</div></div><div class="card"><span class="muted">Average Match</span><div class="metric">${jobs.length?Math.round(jobs.reduce((a,j)=>a+j.score,0)/jobs.length):0}%</div></div></div><div class="section panel"><h3>Match distribution</h3>${jobs.map(j=>`<div class="factor"><span>${esc(j.company)} — ${esc(j.title)}</span><b>${j.score}%</b></div>`).join('')}</div>`;
else if(p==='settings')c=`<div class="profilegrid"><div class="panel"><h3>Matching</h3><div class="factor"><span>Priority threshold</span><b>90%</b></div><div class="factor"><span>Target locations</span><b>${profile.locations.join(' · ')}</b></div></div><div class="panel"><h3>AI</h3><div class="factor"><span>Provider</span><b>${window.aiEnabled?'OpenAI':'Local fallback'}</b></div><div class="factor"><span>Model</span><b>Server environment</b></div></div><div class="panel"><h3>Approval policy</h3><div class="factor"><span>Auto-submit</span><b>OFF</b></div><div class="factor"><span>Unknown facts</span><b>Never infer</b></div><p class="muted">API keys stay server-side. Do not paste secrets into browser JavaScript.</p></div></div>`;
document.getElementById('content').innerHTML=c; if(p==='dashboard')api('/api/health').then(x=>{window.aiEnabled=x.ai;const e=document.getElementById('ai-status');if(e)e.textContent=x.ai?'ON':'LOCAL';}).catch(()=>{});}
function reviewHtml(j){if(!j)return `<div class="panel">No job selected.</div>`;return `<div class="review"><div class="panel"><h3>${esc(j.company)} — ${esc(j.title)}</h3><div class="score">${j.score}%</div><div class="bar"><span style="width:${j.score}%"></span></div><p class="muted">${esc(j.description)}</p><h4>Match breakdown</h4>${Object.entries(j.breakdown||{}).map(([k,v])=>`<div class="factor"><span>${k}</span><b>${v}%</b></div>`).join('')}</div><div class="panel"><h3>AI application package</h3><div id="analysis"><button class="btn primary" onclick="analyze('${j.id}')">Analyze & Generate Package</button></div></div></div>`}
async function addJob(){const company=document.getElementById('company').value.trim(),title=document.getElementById('job-title').value.trim(),location=document.getElementById('location').value.trim(),source=document.getElementById('source').value.trim(),description=document.getElementById('description').value.trim();if(!title||!description)return alert('Please provide at least a job title and full job description.');const j=await api('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({company,title,location,source,description})});jobs=await api('/api/jobs');currentJob=j;render('review');}
async function openReview(id){currentJob=jobs.find(j=>j.id===id)||jobs[0];render('review');}
async function analyze(id){const j=jobs.find(x=>x.id===id);const el=document.getElementById('analysis');el.innerHTML='<p class="muted">Analyzing job against verified profile…</p>';try{const a=await api('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job:j})});el.innerHTML=`<span class="pill green">${a.mode==='openai'?'OpenAI analysis':'Local analysis'}</span><h4>Recommended CV</h4><b>${esc(a.recommended_persona||'Best-fit persona')}</b><h4>Strengths</h4><ul>${(a.strengths||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>Gaps / checks</h4><ul>${(a.gaps||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>Recruiter message</h4><div class="copybox">${esc(a.recruiter_message||'')}</div><h4>Hiring-manager message</h4><div class="copybox">${esc(a.hiring_manager_message||'')}</div><h4>Cover note</h4><div class="copybox">${esc(a.cover_note||'')}</div><div class="alert">⚠ Human checkpoint: salary, work authorization, relocation, notice period and ambiguous screening questions require your confirmation.</div><div class="actions"><button class="btn" onclick="navigator.clipboard.writeText(${JSON.stringify(a.recruiter_message||'')})">Copy recruiter message</button> <button class="btn primary" onclick="approve('${j.id}')">✓ Approve Package</button></div>`;}catch(e){el.innerHTML=`<div class="alert">${esc(e.message)}</div>`}}
async function approve(id){if(!confirm('Approve this package? This does NOT submit an application.'))return;await api('/api/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});jobs=await api('/api/jobs');currentJob=jobs.find(j=>j.id===id);render('review');}
function page(p){render(p)} document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>page(b.dataset.p));load().catch(e=>{document.getElementById('content').innerHTML=`<div class="alert">Could not load app: ${esc(e.message)}. Start the server with <code>npm start</code>.</div>`});
